spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://106.14.168.130/mall_pms
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  #nacos注册中心的名字
  application:
    name: mall-product

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  #主键自增
  global-config:
    db-config:
      id-type: auto
      #逻辑删除
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 10000
logging:
  level:
    cn.xunyi.mall: debug
